name: flutter_alarm_application
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  alarm: ^3.1.7
  url_launcher: ^6.3.0
  audioplayers: ^6.1.0
  shared_preferences: ^2.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/sounds/marimba.mp3
    - assets/sounds/nokia.mp3
    - assets/sounds/mozart.mp3
    - assets/sounds/star_wars.mp3
    - assets/sounds/one_piece.mp3
